server:
  port: 8180
  servlet:
    context-path: /demo
jwt:
  secret: weRpz397hDtgHer43zmlvp23qz8HGtd6fbIlopXcV3876FgsD
  lifetime: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskbroker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher