version: '3'

services:
  application:
    build: .
    ports: ['8180:8180']
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/taskbroker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:14
    ports: ['5432:5432']
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskbroker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db: